In [1]:
import pandas as pd
import numpy as np

### Load CSV Data

In [2]:
df = pd.read_csv('TestSample_100.csv')
df

ID      Cont1     Cont2     Cont3  Ord1  Ord2  Ord3  Nom1  Nom2  Nom3  A  \
0     1   20.08710  15.68590  135.0290     4     2     0     4     3     3  0   
1     2  284.22500   5.51997   74.2780     0     3     3     2     3     3  0   
2     3   62.20010  75.92370   11.6757     1     3     3     4     1     3  0   
3     4   67.25970  38.89740   19.0805     0     0     2     3     2     0  1   
4     5  116.62700  47.63930   63.5971     2     3     4     1     4     1  1   
5     6  265.45400  46.05640   43.1308     4     0     2     2     3     4  1   
6     7   49.75420  16.55880  196.6170     3     1     2     2     0     4  0   
7     8   35.13710  82.08830   50.7249     3     1     0     4     3     3  0   
8     9   26.31330  25.50500  167.5780     0     2     0     1     4     1  1   
9    10  245.07800  45.24770   83.8128     4     1     4     1     4     2  1   
10   11   14.56800  62.73320  134.5180     4     1     0     2     1     0  0   
11   12  186.60200  37.69470   91.7044     4     0     3     0     4     2  1   
12   13    4.78002  40.92060  167.5420     1     3     2     0     0     2  1   
13   14  146.17600  43.30100  103.5940     0     1     1     4     2     0  0   
14   15  200.59100  74.61400  161.3620     4     0     0     0     0     1  0   
15   16   78.63220  88.69100  159.4050     3     4     3     4     0     2  0   
16   17   78.15020  83.50180   71.7606     0     0     1     4     2     1  1   
17   18  258.47400  82.44690  185.7140     1     2     2     3     3     1  1   
18   19  148.40500  32.58340   22.7788     3     4     2     2     4     0  0   
19   20  142.72200  64.54670   55.2326     4     4     1     0     0     1  0   
20   21  169.87100  24.25890   95.8891     3     3     0     3     0     1  0   
21   22  114.20100  19.72060   54.3363     3     1     0     2     4     1  1   
22   23  183.13800  54.86210   56.0423     1     1     2     4     1     0  0   
23   24   58.29430  63.56670  124.1880     4     3     1     2     2     2  0   
24   25    5.07528  87.87240  129.7340     1     4     3     0     1     0  0   
25   26  182.05000  25.89120  153.9580     1     3     2     1     0     0  0   
26   27  131.74600  50.11720  133.3840     2     0     2     2     1     1  1   
27   28  291.20500  57.20810  119.7580     0     2     1     1     3     1  0   
28   29  145.03000  73.47720  148.6610     1     2     0     4     0     1  0   
29   30  104.56400  70.69330  112.7150     4     4     3     1     2     0  0   
..  ...        ...       ...       ...   ...   ...   ...   ...   ...   ... ..   
70   71  294.37800  91.76850   34.5052     3     1     4     2     2     4  0   
71   72  206.38100  83.49630  182.4250     4     2     1     3     3     2  1   
72   73    8.77697  16.27760   45.0009     2     1     3     3     4     0  0   
73   74  165.62300  49.19250   74.5739     4     4     2     3     4     0  1   
74   75  240.76300  80.15950  186.0680     3     3     1     3     1     2  0   
75   76  238.89800   1.58587  193.4230     3     4     4     3     4     2  1   
76   77   53.00840  21.55910   75.0911     3     2     3     3     1     2  0   
77   78  195.46800  65.16780   34.6962     2     4     1     3     1     1  0   
78   79   90.92540  33.74990   26.1581     0     4     4     1     3     1  1   
79   80  243.17100  28.21190  130.0070     2     0     2     2     2     4  0   
80   81  245.45000  20.38090  118.4400     2     1     2     2     3     2  1   
81   82   63.31060  56.42740  128.3310     4     4     0     3     1     3  0   
82   83  159.64800  32.34680  100.7980     4     2     0     4     1     3  1   
83   84  297.00200   6.40575   64.7827     4     1     1     1     1     3  1   
84   85  270.51000   6.03907   84.5695     1     1     2     1     2     1  0   
85   86   29.84150  78.36640   10.1206     2     0     1     0     1     3  0   
86   87  247.71900   4.25153   73.3941     3     2     0     3     1     2  0   
87   88   52.78620  85.66190   17.96

### PreProcess 1: Percentile continuous data to int

In [3]:
q = [10,20,30,40,50,60,70,80,90]

In [4]:
c1 = df['Cont1']
perc_c1 = np.percentile(c1, q)
indices_c1 = np.digitize(c1, perc_c1)
indices_c1

array([0, 9, 2, 2, 4, 9, 1, 1, 0, 8, 0, 6, 0, 5, 6, 3, 3, 9, 5, 5, 5, 3, 6,
       2, 0, 6, 4, 9, 5, 3, 3, 5, 3, 1, 4, 2, 4, 1, 7, 2, 4, 7, 0, 8, 7, 1,
       5, 8, 2, 8, 0, 7, 4, 6, 2, 9, 3, 6, 1, 4, 5, 8, 1, 1, 7, 2, 7, 2, 6,
       9, 9, 7, 0, 5, 8, 7, 1, 6, 3, 8, 8, 2, 5, 9, 9, 0, 8, 1, 6, 3, 4, 8,
       4, 7, 0, 6, 4, 3, 7, 9], dtype=int64)

In [5]:
c2 = df['Cont2']
perc_c2 = np.percentile(c2, q)
indices_c2 = np.digitize(c2, perc_c2)
indices_c2

array([1, 0, 7, 3, 4, 4, 2, 8, 2, 4, 6, 3, 3, 4, 7, 9, 8, 8, 3, 6, 2, 2, 5,
       6, 9, 2, 5, 5, 7, 7, 2, 9, 9, 1, 9, 0, 9, 7, 3, 1, 1, 3, 0, 5, 0, 4,
       6, 0, 7, 1, 1, 7, 1, 7, 8, 1, 3, 8, 6, 7, 6, 0, 5, 4, 5, 5, 8, 4, 4,
       4, 9, 8, 1, 4, 8, 0, 2, 6, 3, 2, 2, 5, 3, 0, 0, 7, 0, 8, 6, 9, 1, 5,
       2, 8, 9, 3, 9, 5, 6, 6], dtype=int64)

In [6]:
c3 = df['Cont3']
perc_c3 = np.percentile(c3, q)
indices_c3 = np.digitize(c3, perc_c3)
indices_c3

array([7, 3, 0, 0, 2, 1, 9, 2, 8, 3, 7, 4, 8, 5, 8, 8, 2, 9, 0, 2, 4, 2, 2,
       6, 6, 7, 6, 6, 7, 5, 8, 5, 1, 5, 4, 4, 4, 9, 3, 4, 4, 9, 4, 1, 7, 7,
       1, 9, 5, 5, 1, 6, 7, 9, 4, 2, 0, 9, 1, 8, 4, 0, 8, 0, 7, 8, 3, 5, 2,
       9, 1, 8, 1, 3, 9, 9, 3, 1, 0, 6, 5, 6, 5, 2, 3, 0, 3, 0, 6, 6, 0, 5,
       3, 7, 3, 2, 8, 7, 1, 6], dtype=int64)

In [7]:
df['Cont1'] = indices_c1
df['Cont2'] = indices_c2
df['Cont3'] = indices_c3
df

ID  Cont1  Cont2  Cont3  Ord1  Ord2  Ord3  Nom1  Nom2  Nom3  A         Y
0     1      0      1      7     4     2     0     4     3     3  0  31.21120
1     2      9      0      3     0     3     3     2     3     3  0  20.84580
2     3      2      7      0     1     3     3     4     1     3  0  94.73210
3     4      2      3      0     0     0     2     3     2     0  1  22.41790
4     5      4      4      2     2     3     4     1     4     1  1  15.07230
5     6      9      4      1     4     0     2     2     3     4  1  21.51730
6     7      1      2      9     3     1     2     2     0     4  0  29.96790
7     8      1      8      2     3     1     0     4     3     3  0   0.48750
8     9      0      2      8     0     2     0     1     4     1  1  63.68780
9    10      8      4      3     4     1     4     1     4     2  1  19.11400
10   11      0      6      7     4     1     0     2     1     0  0  53.28810
11   12      6      3      4     4     0     3     0     4     2  1  12.44830
12   13      0      3      8     1     3     2     0     0     2  1  66.64120
13   14      5      4      5     0     1     1     4     2     0  0  43.07380
14   15      6      7      8     4     0     0     0     0     1  0  28.19820
15   16      3      9      8     3     4     3     4     0     2  0  68.77040
16   17      3      8      2     0     0     1     4     2     1  1  11.34060
17   18      9      8      9     1     2     2     3     3     1  1  89.97470
18   19      5      3      0     3     4     2     2     4     0  0  15.13900
19   20      5      6      2     4     4     1     0     0     1  0  79.84100
20   21      5      2      4     3     3     0     3     0     1  0  35.28860
21   22      3      2      2     3     1     0     2     4     1  1  34.32120
22   23      6      5      2     1     1     2     4     1     0  0   6.97510
23   24      2      6      6     4     3     1     2     2     2  0  69.82670
24   25      0      9      6     1     4     3     0     1     0  0  50.60990
25   26      6      2      7     1     3     2     1     0     0  0  89.66310
26   27      4      5      6     2     0     2     2     1     1  1  44.03130
27   28      9      5      6     0     2     1     1     3     1  0  86.00900
28   29      5      7      7     1     2     0     4     0     1  0   9.96690
29   30      3      7      5     4     4     3     1     2     0  0  28.04530
..  ...    ...    ...    ...   ...   ...   ...   ...   ...   ... ..       ...
70   71      9      9      1     3     1     4     2     2     4  0  90.04900
71   72      7      8      8     4     2     1     3     3     2  1   1.49310
72   73      0      1      1     2     1     3     3     4     0  0  29.11900
73   74      5      4      3     4     4     2     3     4     0  1  68.36810
74   75      8      8      9     3     3     1     3     1     2  0  97.72350
75   76      7      0      9     3     4     4     3     4     2  1  57.23280
76   77      1      2      3     3     2     3     3     1     2  0  17.99150
77   78      6      6      1     2     4     1     3     1     1  0  40.71200
78   79      3      3      0     0     4     4     1     3     1  1  31.36090
79   80      8      2      6     2     0     2     2     2     4  0  36.89510
80   81      8      2      5     2     1     2     2     3     2  1  73.24970
81   82      2      5      6     4     4     0     3     1     3  0  47.68290
82   83      5      3      5     4     2     0     4     1     3  1  74.75850
83   84      9      0      2     4     1     1     1     1     3  1  79.97020
84   85      9      0      3     1     1     2     1     2     1  0  45.62630
85   86      0      7      0     2     0     1     0     1     3  0  70.34850
86   87      8      0      3     3     2     0     3     1     2  0  61.73650
87   88      1      8      0     1     1     1     2     0     4  0  54.95680
88   89      6      6      6     0     4     4     0     4     2  0  56.13110
89   90      3      9      

In [8]:
type(indices_c1)

numpy.ndarray

In [9]:
o1 = df['Ord1'].values
o1

array([4, 0, 1, 0, 2, 4, 3, 3, 0, 4, 4, 4, 1, 0, 4, 3, 0, 1, 3, 4, 3, 3, 1,
       4, 1, 1, 2, 0, 1, 4, 3, 2, 0, 4, 0, 0, 1, 1, 3, 4, 4, 4, 2, 0, 1, 0,
       0, 2, 3, 0, 0, 4, 0, 4, 2, 3, 0, 2, 3, 1, 2, 2, 0, 3, 2, 2, 4, 4, 4,
       2, 3, 4, 2, 4, 3, 3, 3, 2, 0, 2, 2, 4, 4, 4, 1, 2, 3, 1, 0, 3, 4, 2,
       0, 3, 0, 3, 0, 0, 0, 4], dtype=int64)

In [10]:
o2 = df['Ord2'].values
o2

array([2, 3, 3, 0, 3, 0, 1, 1, 2, 1, 1, 0, 3, 1, 0, 4, 0, 2, 4, 4, 3, 1, 1,
       3, 4, 3, 0, 2, 2, 4, 0, 3, 0, 2, 1, 4, 0, 3, 3, 0, 4, 4, 3, 0, 3, 0,
       0, 2, 1, 2, 4, 4, 4, 2, 1, 4, 2, 3, 3, 3, 4, 4, 2, 1, 2, 2, 3, 1, 1,
       3, 1, 2, 1, 4, 3, 4, 2, 4, 4, 0, 1, 4, 2, 1, 1, 0, 2, 1, 4, 3, 3, 3,
       0, 0, 4, 2, 2, 3, 3, 0], dtype=int64)

In [11]:
o3 = df['Ord3'].values
o3

array([0, 3, 3, 2, 4, 2, 2, 0, 0, 4, 0, 3, 2, 1, 0, 3, 1, 2, 2, 1, 0, 0, 2,
       1, 3, 2, 2, 1, 0, 3, 3, 2, 0, 1, 4, 3, 2, 4, 2, 2, 3, 2, 2, 0, 2, 0,
       4, 4, 1, 0, 4, 4, 0, 1, 3, 0, 4, 2, 0, 1, 1, 1, 3, 2, 0, 3, 2, 4, 2,
       0, 4, 1, 3, 2, 1, 4, 3, 1, 4, 2, 2, 0, 0, 1, 2, 1, 0, 1, 4, 1, 2, 4,
       0, 3, 2, 3, 2, 2, 3, 2], dtype=int64)

In [12]:
n1 = df['Nom1'].values
n1

array([4, 2, 4, 3, 1, 2, 2, 4, 1, 1, 2, 0, 0, 4, 0, 4, 4, 3, 2, 0, 3, 2, 4,
       2, 0, 1, 2, 1, 4, 1, 3, 1, 2, 1, 2, 1, 4, 3, 2, 2, 1, 1, 4, 4, 3, 1,
       1, 0, 1, 3, 4, 2, 1, 2, 0, 4, 3, 2, 1, 4, 3, 3, 2, 0, 1, 4, 4, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 2, 2, 3, 4, 1, 1, 0, 3, 2, 0, 3, 1, 3,
       2, 0, 1, 2, 3, 4, 0, 4], dtype=int64)

In [13]:
n2 = df['Nom2'].values
n2

array([3, 3, 1, 2, 4, 3, 0, 3, 4, 4, 1, 4, 0, 2, 0, 0, 2, 3, 4, 0, 0, 4, 1,
       2, 1, 0, 1, 3, 0, 2, 2, 0, 4, 4, 3, 1, 2, 0, 3, 4, 1, 2, 3, 4, 0, 2,
       4, 3, 2, 4, 3, 4, 3, 0, 1, 4, 1, 1, 1, 2, 0, 3, 2, 1, 3, 3, 3, 0, 0,
       3, 2, 3, 4, 4, 1, 4, 1, 1, 3, 2, 3, 1, 1, 1, 2, 1, 1, 0, 4, 3, 0, 1,
       2, 4, 3, 3, 3, 3, 3, 1], dtype=int64)

In [14]:
n3 = df['Nom3'].values
n3

array([3, 3, 3, 0, 1, 4, 4, 3, 1, 2, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0,
       2, 0, 0, 1, 1, 1, 0, 2, 2, 3, 1, 2, 0, 1, 4, 1, 2, 1, 3, 1, 2, 3, 1,
       3, 1, 0, 4, 2, 0, 0, 0, 2, 1, 1, 3, 1, 2, 0, 2, 0, 1, 3, 2, 0, 3, 2,
       2, 4, 2, 0, 0, 2, 2, 2, 1, 1, 4, 2, 3, 3, 3, 1, 3, 2, 4, 2, 2, 0, 2,
       4, 0, 3, 2, 2, 0, 4, 2], dtype=int64)

In [15]:
df.to_csv('TestSample_100_XTable.csv')